name: Update Thinking Garden posts

on:
  schedule:
    - cron: "17 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Thinking Garden posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://taez224.github.io/obsidian/feeds/posts.xml"
          max_post_count: 3
          comment_tag_name: "GARDEN-POST-LIST"
          tag_post_pre_newline: true
          template: "- [$title]($url)$newline"
